### ISSUE TITLE
Update training plan approval notebooks after refactoring

### ISSUE THREAD

**Issue by sharkovsky** [fedbiomed/fedbiomed#1041]
Edit training plan approval notebook, since there is a change in the function API

**Comment by srcansiz** [comment]
Hi @ybouilla, 

Since you are working on updating notebooks and docs,  I wanted to give you more details about this issue. Training plan approval notebooks (in docs and notebooks) are failing while calling `set_training_plan_class`. It is due to  updated torch Model in the second training plan has not the same model weights.  To solve the issue, `set_training_plan_class` should be called with argument `keep_weights=False`.
