### ISSUE TITLE
In the `Experiment` refactoring, `set_model_args` fails if used before `set_training_args`

### ISSUE THREAD

**Issue by ybouilla** [fedbiomed/fedbiomed#1048]
Bug introduced while doing the refactoring of `Experiment` (see #896 )

if one executes all the methods to configure an `Experiment`
```
from fedbiomed.researcher.experiment import Experiment
exp = Experiment()
exp.set_training_plan_class(training_plan_class=MyTrainingPlan)
exp.set_model_args(model_args={}) 
>>> fails with following error
 File "/home/ybouilla/Documents/github/fedbiomed/fedbiomed/common/training_plans/_torchnn.py", line 257, in _configure_model_and_optimizer
    optimizer = self.init_optimizer(self._optimizer_args)
KeyError: 'lr'
```

but if one runs 
```
training_args = {
    'loader_args': { 'batch_size': 48, }, 
    'optimizer_args': {
        'lr': 1e-3, 
    },
    'epochs': 1, 
}
exp.set_training_args(training_args=training_args)
exp.set_model_args(model_args={}) 
```
`Experiment` can be run
**proposal**: after discussion with Francesco, we should add a default `lr` value (simplest solution we could find)

**Comment by srcansiz** [comment]
Hi @ybouilla, 

> proposal: after discussion with Francesco, we should add a default lr value (simplest solution we could find)

Thank you for spotting this issue but unfortunately  it seems more complicated than that.  There may be other parameters set by the user within the `init_optimizer` method depending on the optimizer that is used. Therefore, adding `lr`  will just avoid the error in this specific notebook. 

It seems to me that `model_args` and `training_args` are dependent in the sense that they both are required to build a training plan object. On the other hand, `optimizer_args` are not necessary on the researcher side since there is no training (please correct me if I am wrong). it is more or less just for verifying `init_optimizer` method is well defined. However, we do not do any check fro `training_data`.  Finally, I will have two proposals, 

1 - To me training arguments does not seems that very functional on the researcher side. Therefore, making `training_args` optional and adding condition in `post_init` to set attributes related `training_args` if it is existing may be an option to fix such issues.  However,  this may require decent amount of changes in BaseTrainingPlan and its children. It may require changing the way that random seed is set.

2 - Add a new argument `build_optimizer` to `post_init`, and set default as `True`. Call `post_init` as `build_optimizer=False` on the researcher side. 

3 - More advance and radical change: Create a `TrainingPlanBuilder` class that is responsible of all consistency checks regarding where the training plan is going to be built (researcher or node). This class will be more advance implementation of the current `post_init` and also `instantiate_training_plan` method. 

For now I would vote for 2 if we are sure that optimizer is not used on the researcher at all.
