### ISSUE TITLE
[New issue]: Import a custom function as a dependency

### ISSUE THREAD

**Issue by manos-mark** [fedbiomed/fedbiomed#1164]
I need to import some custom functions and classes during the definition of the `TrainingPlan`. I have placed them in python scripts at the same directory of the Researcher's Jupyter Notebook and I try to import them on the notebook and place them also in the `init_dependencies`.

My code looks like this:
```
from fedbiomed.common.training_plans import TorchTrainingPlan
import my_custom_script

class MyTrainingPlan(TorchTrainingPlan):
    def init_model(self, model_args):
        ...
    def init_optimizer(self, optimizer_args):
        ...
    def init_dependencies(self):
        deps = [
            'import my_custom_script',
        ]
        return deps
````

When the experiment is running i get this error:
`
ERROR - Training failed for node NODE_d696dc84-...: Cannot instantiate training plan object.
`

As I read in the documentation, this is not possible because those custom functions are not supported by Fed-BioMed. 
_You should define the init_dependencies to declare the modules that are used in the training plan. The modules should be supported by the Fed-BioMed._

A possible solution is to implement my custom functions inside `MyTrainingPlan` but this is not optimal. Is there another way?
Also, my previous assumption based on the documentation is true, I can't use any library that is not supported by Fed-BioMed (i.e. duckdb). Is there a list with the supported libraries?

**Comment by srcansiz** [comment]
> I need to import some custom functions and classes during the definition of the `TrainingPlan`. I have placed them in python scripts at the same directory of the Researcher's Jupyter Notebook and I try to import them on the notebook and place them also in the `init_dependencies`.
> 
> My code looks like this:
> 
> ```
> from fedbiomed.common.training_plans import TorchTrainingPlan
> import my_custom_script
> 
> class MyTrainingPlan(TorchTrainingPlan):
>     def init_model(self, model_args):
>         ...
>     def init_optimizer(self, optimizer_args):
>         ...
>     def init_dependencies(self):
>         deps = [
>             'import my_custom_script',
>         ]
>         return deps
> ```
> 
> When the experiment is running i get this error: `ERROR - Training failed for node NODE_d696dc84-...: Cannot instantiate training plan object.`
> 
> As I read in the documentation, this is not possible because those custom functions are not supported by Fed-BioMed. _You should define the init_dependencies to declare the modules that are used in the training plan. The modules should be supported by the Fed-BioMed._
> 
> A possible solution is to implement my custom functions inside `MyTrainingPlan` but this is not optimal. Is there another way? 

Hi @manos-mark,

Due to security reasons it is not possible use the modules that are created on the researcher side. Your custom scripts/classes/functions should be part of the training plan. This allows node owner to verify the code that is going to be executed on the node side. 

However, if you are using Fed-BioMed in development/test mode, meaning that you do not have security concerns, I suggest you to add your modules/scripts in to `fedbiomed` root directory.  Then distribute your Fed-BioMed source files among the nodes, and start nodes using this new Fed-BioMed folder. 

> Also, my previous assumption based on the documentation is true, I can't use any library that is not supported by Fed-BioMed (i.e. duckdb). Is there a list with the supported libraries?

You can check conda environment files in `envs/development/conda`. You will see list of python libraries. You can add a new library using this environment files. Please also make sure that those libraries are added and environment are updated on the machines that the nodes are running.

**Comment by manos-mark** [comment]
Thank you very much!
