### ISSUE TITLE
Feature/513 Fix warnings in `TorchModel.set_weights` and BatchNorm layers' handling - [merged]

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#746]
In GitLab by @pandrey-fr on Apr 24, 2023, 18:04

_Merges feature/513-torch-model-set-weights-warnings -> develop_

This MR addresses issue #513, which is about `TorchModel.set_weights` generating warnings when the model's state dict comprises tensors or values that are not part of the model's parameters.

The suggested fix is merely to add a secondary filter on these warnings so that it is expected that input weights would not cover these values (and may even exclude non-trainable weights), out of coherence with the `get_weights` counterpart method's outputs.

**Edit**: the initial issue emerged from the presence of BatchNorm layers, the handling of which has its importance in a federated context. As such, and based on exchanges that can be found on the issue's page, this MR was also made to:
- share non-`torch.nn.Parameter` model states at the end of rounds so that they are aggregated
- implement a new training arg (as an optional boolean flag, the default value of which is True) to enable not sharing these values (although in the current state of things that is not recommended - see #529)

**Comment by ybouilla** [comment]
This issue has been reopen because the fix didnot cover the learning rate extraction from pytorch model: some of the layers didnot present a learning rate, and thus cannot be used in the native scaffold implementation (leading to actually to the following error:
` File "/home/ybouilla/github/fedbiomed_ssh/fedbiomed/fedbiomed/researcher/aggregators/scaffold.py", line 251, in <dictcomp>
    key: d_i[key] + val / (self.nodes_lr[node_id][idx] * n_updates)
IndexError: list index out of range
`

**Comment by sharkovsky** [comment]
This as now been fixed by #826
