### ISSUE TITLE
update DecLearn version used 

### ISSUE THREAD

**Issue by mvesin** [fedbiomed/fedbiomed#854]
@pandrey-fr submitted:

> DecLearn v2.3 has been released last week, including a few new features that are mostly out of scope for Fed-BioMed, but also 
> a number of bug fixes (the most important ones of which have been backported to previous versions via subminor version 
> releases) that you might not want to miss out on. An easy solution might be to specify that Fed-BioMed requires 
> declearn[torch1] >=2.3.1,<3.0. Note that for v2.3, you may either specify [torch], [torch1] or [torch2], as we have added support 
> for Torch 2.0. If you force end-users to install declearn v2.3 or above, it would make sense to me to use one of the two latter 
> specifiers rather than the generic one, in accordance with FBM's own support (which AFAIK is targetted at Torch 1.13 for now).

We will use `declearn[torch1] ~= 2.3.0` to be coherent with current version specifications for other dependencies (be strict to limit errors coming from incompatible dependencies when versions evolve).

**Comment by mvesin** [comment]
hi @pandrey-fr 
when testing it appears there are conflicting requirements between:
- declearn[torch1] 2.3.0 => `opacus ~=1.3.0`
- fedbiomed current version => `opacus ~=1.4.0`

So we should probably keep using DecLearn 2.1 in Fed-BioMed until you release a version of `declearn[torch1]` compatible with `opacus 1.4`.

**Comment by pandrey-fr** [comment]
Hi @mvesin sorry for not getting back to you earlier about that.
I think we made this change due to an incompatibility between FuncTorch and Opacus 1.4, but I might be mistaken. I will run some new tests regarding that.

Note that as an alternative you could use:
```
declearn ~= 2.3.0
functorch ~= 1.13.0
```

This way the Torch and Opacus dependencies specifications from Fed-BioMed will be used, but you will still be able to use the Torch capabilities of Declearn (including DP-oriented features backed by FuncTorch and Opacus).

**Comment by pandrey-fr** [comment]
OK, it turns out that with PyTorch >= 1.13, there is no need to install functorch as a separate package. I am going to push an update to our installation rules and release a subminor version (2.3.2) that will smooth things, by having the "torch", "torch1" and "torch2" extra specifies target only torch. This way FBM will be able to require `declearn[torch1] ~=2.3.2`.

Otherwise, if you would rather stick to 2.2, it would be nice to push to `~=2.2.1`, to ensure backported backend math fixes are installed.

**Comment by pandrey-fr** [comment]
Done; declearn version 2.3.2 is now out, with updated extra specifiers for torch.

Fed-BioMed should be able to specify `declearn[torch1]~=2.3.2` as a dependency without a clash with its torch and opacus requirements.

Note that otherwise, you may require `declearn ~= <version>` without asking explicitly for torch extra dependencies, since FBM already takes care of requiring Torch 1.13 and FuncTorch is automatically installed together with it.

**Comment by mvesin** [comment]
Thank you @pandrey-fr 

I tested `declearn[torch1]~=2.3.2` in the context of #856 
It seems to work fine, so I plan to include/merge it with the gRPC communications branch
