### ISSUE TITLE
reorganize notebooks and tutorials

### ISSUE THREAD

**Issue by mvesin** [fedbiomed/fedbiomed#974]
Reorganize notebooks and tutorials:
    - eg: from `doc/tutorials` + `notebooks/` => `doc/tutorials` (user oriented) + `samples/` (examples without a fully documented case for the user and for the developer) + `end2endtests` (to be run in CI)
    - eg: split them to avoid duplicates (eg: 1 notebook for all data loading ? for defining "base" models ? end2end tests execute several notebooks in a row ?)

- [ ] define notebook/tutorials new organization
- [ ] implement
- [ ] user review
- [ ] end2end tests

To be discussed with:
- PO & users: how tutorials and notebooks should appear
- dev (eg end2end test dev): how to have it work

**Comment by srcansiz** [comment]
Several ideas from the dicussion with @mvesin  and @ybouilla, 

- Notebooks directory: 
  - Good for developer or user because they are used to enter notebooks directory to run examples.
  - Important: save notebook results (images or some result) as image and add into notebook statically 
  - Notebooks directory:
    -  Remove the notebooks that are already existing in `docs/tutorials` 
    -  Simplify notebooks by removing dataset load parts etc. and make it more advance Fed-BioMed user oriented by removing unnecessary definitions. 
    - Create a link to `docs/tutorials` from notebooks directory
- End-to-end: 
  - Create a different folder to keep end-to-end tests
